# Generated by Django 5.0.6 on 2024-06-27 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gifts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("creator", models.CharField(max_length=255)),
                ("img", models.ImageField(upload_to="gifts/images")),
                ("description", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gift",
                "verbose_name_plural": "Gifts",
            },
        ),
    ]
