# Generated by Django 5.0.6 on 2024-06-29 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0002_bithday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bithday",
        ),
    ]
